from __future__ import annotations

import argparse
import json
import os
import re
import struct
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from ..common.snapshot import (
    find_bundle_name_in_report,
    load_snapshot_payload,
    resolve_route_scope,
    resolve_snapshot_file,
)
from ..common.validate import validate_table_name
from ..config import (
    DEFAULT_GET_OUTPUT_DIR,
    DEFAULT_ROUTE,
    DEFAULT_SNAPSHOT_FILE,
    DEFAULT_STR_REPORT_FILE,
    LEGACY_SNAPSHOT_FILE,
)
from ..paths import resolve_repo_path

try:
    import psycopg
except ImportError as exc:  # pragma: no cover
    raise SystemExit("psycopg is required. Install it with: pip install 'psycopg[binary]'") from exc

try:
    import UnityPy
except ImportError as exc:  # pragma: no cover
    raise SystemExit("UnityPy is required. Install it with: pip install UnityPy") from exc

TEXT_COLUMNS = ("cn_s", "en", "jp", "cn_t")


def _resolve_snapshot_file(path: Path) -> Path:
    return resolve_snapshot_file(
        path=path,
        default_snapshot_file=DEFAULT_SNAPSHOT_FILE,
        legacy_snapshot_file=LEGACY_SNAPSHOT_FILE,
    )


@dataclass
class Scope:
    version: str
    revision: str
    report_path: Path
    scope_dir: Path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare latest INT_STEAM STR TextAssets against astral_data and optionally upload changes"
    )
    parser.add_argument("--input-root", default=DEFAULT_GET_OUTPUT_DIR, help="Base input directory")
    parser.add_argument("--version", default="", help="Optional version override")
    parser.add_argument("--revision", default="", help="Optional revision override")
    parser.add_argument(
        "--snapshot-file",
        default=DEFAULT_SNAPSHOT_FILE,
        help="Snapshot metadata path generated by assets-get",
    )
    parser.add_argument("--db-table", default="astral_data", help="Data table name")
    parser.add_argument("--logs-table", default="astral_logs", help="Logs table name")
    parser.add_argument("--asset-prefix", default="STR", help="TextAsset name prefix filter")
    parser.add_argument("--report-file", default=DEFAULT_STR_REPORT_FILE, help="Report path")
    parser.add_argument(
        "--upload-db",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Apply comparison result to database tables (disable with --no-upload-db)",
    )
    parser.add_argument("--log-source", default="SYNC", help="astral_logs.source value")
    parser.add_argument("--log-status", default="APPROVED", help="astral_logs.status value")
    return parser.parse_args(argv)


def _read_varint(data: bytes, offset: int) -> tuple[int, int]:
    value = 0
    shift = 0
    while True:
        if offset >= len(data):
            raise IndexError("Unexpected end while reading varint")
        byte = data[offset]
        offset += 1
        value |= (byte & 0x7F) << shift
        if not (byte & 0x80):
            break
        shift += 7
    return value, offset


def _parse_proto_entries(data: bytes) -> list[dict[str, Any]]:
    entries_map: dict[int, dict[str, Any]] = {}
    start_offset = -1

    probe_limit = min(500, max(0, len(data) - 100))
    for i in range(probe_limit):
        if data[i] not in (0x0A, 0x12):
            continue
        try:
            size_val, next_off = _read_varint(data, i + 1)
        except Exception:
            continue
        if 0 < size_val < 5000 and next_off < len(data) and data[next_off] == 0x0D:
            start_offset = i
            break

    if start_offset == -1:
        return []

    offset = start_offset
    while offset < len(data):
        try:
            _, offset = _read_varint(data, offset)
            length, offset = _read_varint(data, offset)
        except Exception:
            break

        entry_end = offset + length
        if entry_end > len(data):
            break

        entry_data: dict[str, Any] = {"id": 0, "cn_s": "", "en": "", "jp": "", "cn_t": ""}
        curr = offset
        while curr < entry_end:
            try:
                f_tag_val, f_new_offset = _read_varint(data, curr)
            except Exception:
                break

            f_num = f_tag_val >> 3
            f_wire = f_tag_val & 7
            curr = f_new_offset

            try:
                if f_wire == 0:
                    _, curr = _read_varint(data, curr)
                elif f_wire == 1:
                    curr += 8
                elif f_wire == 5:
                    val = struct.unpack("<I", data[curr:curr + 4])[0]
                    curr += 4
                    if f_num == 1:
                        entry_data["id"] = int(val)
                elif f_wire == 2:
                    s_len, curr = _read_varint(data, curr)
                    s_content = data[curr:curr + s_len]
                    curr += s_len
                    text = s_content.decode("utf-8")
                    if f_num == 2:
                        entry_data["cn_s"] = text
                    elif f_num == 3:
                        entry_data["en"] = text
                    elif f_num == 4:
                        entry_data["jp"] = text
                    elif f_num == 5:
                        entry_data["cn_t"] = text
                else:
                    break
            except Exception:
                break

        entry_id = int(entry_data.get("id", 0))
        if entry_id != 0 and entry_id not in entries_map:
            entries_map[entry_id] = entry_data

        offset = entry_end

    return list(entries_map.values())


def _decode_blob(value: Any) -> bytes:
    if isinstance(value, (bytes, bytearray)):
        return bytes(value)
    if isinstance(value, str):
        return value.encode("utf-8", "surrogateescape")
    return bytes(value)


def _extract_str_assets(bundle_path: Path, asset_prefix: str) -> dict[str, dict[int, dict[str, str]]]:
    env = UnityPy.load(str(bundle_path))
    extracted: dict[str, dict[int, dict[str, str]]] = {}

    for obj in env.objects:
        if getattr(getattr(obj, "type", None), "name", "") != "TextAsset":
            continue

        asset = obj.read()
        name = str(getattr(asset, "m_Name", "") or "")
        if not name.startswith(asset_prefix):
            continue

        raw = _decode_blob(getattr(asset, "m_Script", b""))
        parsed_entries = _parse_proto_entries(raw)
        if not parsed_entries:
            continue

        category_rows: dict[int, dict[str, str]] = {}
        for item in parsed_entries:
            entry_id = int(item.get("id", 0))
            if entry_id == 0:
                continue
            category_rows[entry_id] = {
                "cn_s": str(item.get("cn_s", "") or ""),
                "en": str(item.get("en", "") or ""),
                "jp": str(item.get("jp", "") or ""),
                "cn_t": str(item.get("cn_t", "") or ""),
            }

        if category_rows:
            extracted[name] = category_rows

    return extracted


def _find_latest_scope(input_root: Path, version: str, revision: str) -> Scope:
    route_root = input_root / DEFAULT_ROUTE
    if not route_root.exists():
        raise FileNotFoundError(f"Route directory not found: {route_root}")

    if version and revision:
        scope_dir = route_root / version / revision
        report_path = scope_dir / "report.json"
        if not report_path.exists():
            raise FileNotFoundError(f"report.json not found: {report_path}")
        return Scope(version=version, revision=revision, report_path=report_path, scope_dir=scope_dir)

    if (version and not revision) or (revision and not version):
        raise ValueError("--version and --revision must be provided together")

    report_candidates = list(route_root.glob("*/*/report.json"))
    if not report_candidates:
        raise FileNotFoundError(f"No report.json found under: {route_root}")

    latest_report = max(report_candidates, key=lambda p: p.stat().st_mtime)
    latest_revision = latest_report.parent.name
    latest_version = latest_report.parent.parent.name
    return Scope(
        version=latest_version,
        revision=latest_revision,
        report_path=latest_report,
        scope_dir=latest_report.parent,
    )


def _load_scope_from_snapshot(snapshot_file: Path, input_root: Path, route: str) -> Scope:
    payload = load_snapshot_payload(snapshot_file)
    version, revision = resolve_route_scope(payload, route, snapshot_file)

    scope_dir = input_root / route / version / revision
    report_path = scope_dir / "report.json"
    if not report_path.exists():
        raise FileNotFoundError(f"report.json not found: {report_path}")

    return Scope(version=version, revision=revision, report_path=report_path, scope_dir=scope_dir)


def _find_strcard_bundle(report_path: Path) -> str:
    return find_bundle_name_in_report(
        report_path,
        asset_type="TextAsset",
        asset_name="STRCard",
        not_found_message="STRCard TextAsset bundle not found in report.json",
    )


def _validate_table_name(table_name: str) -> str:
    return validate_table_name(table_name)


def _normalize(value: str) -> str:
    return (value or "").replace("\r\n", "\n")


def _coerce_db_key(entry_key: str) -> Any:
    if re.fullmatch(r"-?[0-9]+", entry_key):
        return int(entry_key)
    return entry_key


def _fetch_db_rows(database_url: str, table_name: str, categories: list[str]) -> dict[tuple[str, str], dict[str, str]]:
    if not categories:
        return {}

    sql = (
        f'SELECT category, "key", cn_s, en, jp, cn_t '
        f"FROM {table_name} "
        f"WHERE is_deleted = false AND category = ANY(%s)"
    )

    rows_map: dict[tuple[str, str], dict[str, str]] = {}
    with psycopg.connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (categories,))
            for row in cur.fetchall():
                category = str(row[0] or "")
                entry_key = str(row[1] or "").strip()
                if not entry_key:
                    continue
                rows_map[(category, entry_key)] = {
                    "cn_s": str(row[2] or ""),
                    "en": str(row[3] or ""),
                    "jp": str(row[4] or ""),
                    "cn_t": str(row[5] or ""),
                }
    return rows_map


def _build_comparison(
    extracted: dict[str, dict[int, dict[str, str]]],
    db_rows: dict[tuple[str, str], dict[str, str]],
) -> dict[str, Any]:
    extracted_keys: set[tuple[str, str]] = set()
    missing_in_db: list[dict[str, Any]] = []
    mismatches: list[dict[str, Any]] = []

    for category, rows in extracted.items():
        for entry_id, values in rows.items():
            entry_key = str(entry_id)
            composite_key = (category, entry_key)
            extracted_keys.add(composite_key)

            db_values = db_rows.get(composite_key)
            if db_values is None:
                missing_in_db.append({"category": category, "id": entry_id})
                continue

            for field in TEXT_COLUMNS:
                bundle_value = _normalize(values.get(field, ""))
                db_value = _normalize(db_values.get(field, ""))
                if bundle_value != db_value:
                    mismatches.append(
                        {
                            "category": category,
                            "id": entry_id,
                            "field": field,
                            "bundle_value": bundle_value,
                            "db_value": db_value,
                        }
                    )

    db_only: list[dict[str, Any]] = []
    for (category, entry_key) in sorted(db_rows.keys()):
        if (category, entry_key) in extracted_keys:
            continue
        try:
            output_id: Any = int(entry_key)
        except ValueError:
            output_id = entry_key
        db_only.append({"category": category, "id": output_id})

    mismatch_row_keys = {(item["category"], item["id"]) for item in mismatches}
    return {
        "missing_in_db": missing_in_db,
        "db_only": db_only,
        "mismatches": mismatches,
        "mismatch_row_count": len(mismatch_row_keys),
        "mismatch_field_count": len(mismatches),
    }


def _build_db_actions(
    extracted: dict[str, dict[int, dict[str, str]]],
    db_rows: dict[tuple[str, str], dict[str, str]],
) -> dict[str, list[dict[str, Any]]]:
    creates: list[dict[str, Any]] = []
    updates: list[dict[str, Any]] = []
    deletes: list[dict[str, Any]] = []

    extracted_keys: set[tuple[str, str]] = set()

    for category, rows in extracted.items():
        for entry_id, raw_values in rows.items():
            entry_key = str(entry_id)
            composite_key = (category, entry_key)
            extracted_keys.add(composite_key)

            new_values = {field: _normalize(raw_values.get(field, "")) for field in TEXT_COLUMNS}
            existing_values = db_rows.get(composite_key)

            if existing_values is None:
                creates.append(
                    {
                        "category": category,
                        "id": entry_id,
                        "entry_key": entry_key,
                        "new_values": new_values,
                    }
                )
                continue

            old_values = {field: _normalize(existing_values.get(field, "")) for field in TEXT_COLUMNS}
            changed_old: dict[str, str] = {}
            changed_new: dict[str, str] = {}
            for field in TEXT_COLUMNS:
                if old_values[field] != new_values[field]:
                    changed_old[field] = old_values[field]
                    changed_new[field] = new_values[field]

            if changed_new:
                updates.append(
                    {
                        "category": category,
                        "id": entry_id,
                        "entry_key": entry_key,
                        "old_values": changed_old,
                        "new_values": changed_new,
                        "full_new_values": new_values,
                    }
                )

    for (category, entry_key), existing_values in sorted(db_rows.items()):
        if (category, entry_key) in extracted_keys:
            continue

        old_values = {field: _normalize(existing_values.get(field, "")) for field in TEXT_COLUMNS}
        try:
            output_id: Any = int(entry_key)
        except ValueError:
            output_id = entry_key

        deletes.append(
            {
                "category": category,
                "id": output_id,
                "entry_key": entry_key,
                "old_values": old_values,
            }
        )

    return {
        "creates": creates,
        "updates": updates,
        "deletes": deletes,
    }


def _apply_db_actions(
    database_url: str,
    data_table: str,
    logs_table: str,
    actions: dict[str, list[dict[str, Any]]],
    asset_version: str,
    log_source: str,
    log_status: str,
) -> dict[str, Any]:
    creates = actions["creates"]
    updates = actions["updates"]
    deletes = actions["deletes"]

    upsert_rows: list[tuple[Any, ...]] = []
    delete_rows: list[tuple[Any, ...]] = []
    log_rows: list[tuple[Any, ...]] = []

    batch_id = str(uuid.uuid4())

    for item in creates:
        key_for_db = _coerce_db_key(item["entry_key"])
        values = item["new_values"]
        upsert_rows.append(
            (
                item["category"],
                key_for_db,
                values["cn_s"],
                values["en"],
                values["jp"],
                values["cn_t"],
            )
        )
        log_rows.append(
            (
                item["category"],
                key_for_db,
                "CREATE",
                None,
                json.dumps(values, ensure_ascii=False),
                log_source,
                batch_id,
                log_status,
                asset_version,
            )
        )

    for item in updates:
        key_for_db = _coerce_db_key(item["entry_key"])
        full_new = item["full_new_values"]
        upsert_rows.append(
            (
                item["category"],
                key_for_db,
                full_new["cn_s"],
                full_new["en"],
                full_new["jp"],
                full_new["cn_t"],
            )
        )
        log_rows.append(
            (
                item["category"],
                key_for_db,
                "UPDATE",
                json.dumps(item["old_values"], ensure_ascii=False),
                json.dumps(item["new_values"], ensure_ascii=False),
                log_source,
                batch_id,
                log_status,
                asset_version,
            )
        )

    for item in deletes:
        key_for_db = _coerce_db_key(item["entry_key"])
        delete_rows.append((item["category"], key_for_db))
        log_rows.append(
            (
                item["category"],
                key_for_db,
                "DELETE",
                json.dumps(item["old_values"], ensure_ascii=False),
                None,
                log_source,
                batch_id,
                log_status,
                asset_version,
            )
        )

    upsert_sql = (
        f"INSERT INTO {data_table} "
        f"(category, \"key\", cn_s, en, jp, cn_t, is_deleted, updated_at, latest_log_status, latest_log_date, last_sync_at) "
        f"VALUES (%s, %s, %s, %s, %s, %s, false, NOW(), 'APPROVED', NOW(), NOW()) "
        f"ON CONFLICT (category, \"key\") DO UPDATE SET "
        f"cn_s = EXCLUDED.cn_s, "
        f"en = EXCLUDED.en, "
        f"jp = EXCLUDED.jp, "
        f"cn_t = EXCLUDED.cn_t, "
        f"is_deleted = false, "
        f"updated_at = NOW(), "
        f"latest_log_status = CASE WHEN {data_table}.latest_log_status = 'PENDING' THEN 'PENDING' ELSE 'APPROVED' END, "
        f"latest_log_date = NOW(), "
        f"last_sync_at = NOW()"
    )

    delete_sql = f'UPDATE {data_table} SET is_deleted = true, updated_at = NOW() WHERE category = %s AND "key" = %s'

    log_sql = (
        f"INSERT INTO {logs_table} "
        f"(category, \"key\", action_type, old_value, new_value, source, batch_id, status, asset_version) "
        f"VALUES (%s, %s, %s, %s::jsonb, %s::jsonb, %s, %s, %s, %s)"
    )

    with psycopg.connect(database_url) as conn:
        with conn.cursor() as cur:
            if upsert_rows:
                cur.executemany(upsert_sql, upsert_rows)
            if delete_rows:
                cur.executemany(delete_sql, delete_rows)
            if log_rows:
                cur.executemany(log_sql, log_rows)
        conn.commit()

    return {
        "batch_id": batch_id,
        "create_count": len(creates),
        "update_count": len(updates),
        "delete_count": len(deletes),
        "upsert_count": len(upsert_rows),
        "log_count": len(log_rows),
    }


def main(argv: list[str] | None = None) -> int:
    load_dotenv()
    args = parse_args(argv)
    args.input_root = resolve_repo_path(args.input_root).as_posix()
    args.report_file = resolve_repo_path(args.report_file).as_posix()
    args.snapshot_file = resolve_repo_path(args.snapshot_file).as_posix()

    input_root = Path(args.input_root)

    version_arg = args.version.strip()
    revision_arg = args.revision.strip()
    if bool(version_arg) ^ bool(revision_arg):
        raise SystemExit("--version and --revision must be provided together")

    snapshot_file = _resolve_snapshot_file(Path(str(args.snapshot_file or DEFAULT_SNAPSHOT_FILE)))
    if version_arg and revision_arg:
        scope = _find_latest_scope(input_root, version_arg, revision_arg)
        scope_source = "cli"
    else:
        scope = _load_scope_from_snapshot(snapshot_file, input_root, DEFAULT_ROUTE)
        scope_source = "snapshot"

    bundle_name = _find_strcard_bundle(scope.report_path)
    bundle_path = scope.scope_dir / bundle_name
    if not bundle_path.exists():
        raise FileNotFoundError(f"Bundle file not found: {bundle_path}")

    extracted = _extract_str_assets(bundle_path, args.asset_prefix)
    categories = sorted(extracted.keys())

    database_url = os.getenv("DATABASE_URL", "").strip()
    if not database_url:
        raise SystemExit("DATABASE_URL is not set")

    data_table = _validate_table_name(args.db_table)
    logs_table = _validate_table_name(args.logs_table)

    db_rows = _fetch_db_rows(database_url, data_table, categories)
    comparison = _build_comparison(extracted, db_rows)
    actions = _build_db_actions(extracted, db_rows)

    total_entries = sum(len(rows) for rows in extracted.values())
    report_path = Path(str(args.report_file or DEFAULT_STR_REPORT_FILE))
    report_path.parent.mkdir(parents=True, exist_ok=True)

    asset_version = f"{scope.version}.{scope.revision}"
    db_apply: dict[str, Any] = {
        "enabled": bool(args.upload_db),
        "asset_version": asset_version,
        "create_count": len(actions["creates"]),
        "update_count": len(actions["updates"]),
        "delete_count": len(actions["deletes"]),
        "applied": False,
        "batch_id": "",
        "log_count": 0,
    }

    if bool(args.upload_db):
        applied = _apply_db_actions(
            database_url=database_url,
            data_table=data_table,
            logs_table=logs_table,
            actions=actions,
            asset_version=asset_version,
            log_source=args.log_source,
            log_status=args.log_status,
        )
        db_apply.update(applied)
        db_apply["applied"] = True

    report_payload = {
        "summary": {
            "route": DEFAULT_ROUTE,
            "version": scope.version,
            "revision": scope.revision,
            "scope_source": scope_source,
            "snapshot_file": snapshot_file.as_posix(),
            "scope_dir": scope.scope_dir.as_posix(),
            "report_source": scope.report_path.as_posix(),
            "bundle_name": bundle_name,
            "bundle_path": bundle_path.as_posix(),
            "asset_prefix": args.asset_prefix,
            "categories_count": len(categories),
            "extracted_entry_count": total_entries,
            "db_row_count": len(db_rows),
            "missing_in_db_count": len(comparison["missing_in_db"]),
            "db_only_count": len(comparison["db_only"]),
            "mismatch_row_count": comparison["mismatch_row_count"],
            "mismatch_field_count": comparison["mismatch_field_count"],
            "upload_db": bool(args.upload_db),
            "data_table": data_table,
            "logs_table": logs_table,
        },
        "comparison": {
            "missing_in_db": comparison["missing_in_db"],
            "db_only": comparison["db_only"],
            "mismatches": comparison["mismatches"],
        },
        "db_apply": db_apply,
    }

    report_path.write_text(json.dumps(report_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    print(
        "[assets-str] "
        f"route={DEFAULT_ROUTE} version={scope.version} revision={scope.revision} "
        f"categories={len(categories)} extracted={total_entries} mismatches={comparison['mismatch_field_count']} "
        f"missing_in_db={len(comparison['missing_in_db'])} db_only={len(comparison['db_only'])} "
        f"upload_db={bool(args.upload_db)} report={report_path.as_posix()}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
