from __future__ import annotations

import argparse
import html
import json
import os
import re
import uuid
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET

from ..common.snapshot import load_snapshot_payload, resolve_route_scope, resolve_snapshot_file
from ..common.validate import validate_table_name
from ..config import (
    DEFAULT_GET_OUTPUT_DIR,
    DEFAULT_LANG_REPORT_FILE,
    DEFAULT_ROUTE,
    DEFAULT_SNAPSHOT_FILE,
    LEGACY_SNAPSHOT_FILE,
)
from ..paths import resolve_repo_path

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    def load_dotenv() -> bool:
        return False

try:
    import psycopg
except ImportError:  # pragma: no cover
    psycopg = None  # type: ignore[assignment]

try:
    import UnityPy
except ImportError as exc:  # pragma: no cover
    raise SystemExit("UnityPy is required. Install it with: pip install UnityPy") from exc


def _resolve_snapshot_file(path: Path) -> Path:
    return resolve_snapshot_file(
        path=path,
        default_snapshot_file=DEFAULT_SNAPSHOT_FILE,
        legacy_snapshot_file=LEGACY_SNAPSHOT_FILE,
    )


COLUMNS = ["name", "cn_s", "en", "jp", "cn_t", "ko"]
TARGET_TEXT_ASSETS = {
    "simplified chinese": "cn_s",
    "english": "en",
    "japanese": "jp",
    "traditional chinese": "cn_t",
}
STRING_TAG_PATTERN = re.compile(
    r"<string\b[^>]*\bname=\"([^\"]+)\"[^>]*>(.*?)</string>",
    re.IGNORECASE | re.DOTALL,
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract language TextAssets and sync lang_data/lang_logs (DB-only)"
    )
    parser.add_argument("--version", default="", help="Optional version path segment, e.g. 3.0.1")
    parser.add_argument("--revision", default="", help="Optional revision path segment, e.g. 926")
    parser.add_argument(
        "--input-root",
        default=DEFAULT_GET_OUTPUT_DIR,
        help="Base input root that contains route/version/revision folders",
    )
    parser.add_argument("--report-file", default=DEFAULT_LANG_REPORT_FILE, help="JSON report output path")
    parser.add_argument(
        "--snapshot-file",
        default=DEFAULT_SNAPSHOT_FILE,
        help="Snapshot metadata path generated by assets-get",
    )
    parser.add_argument(
        "--sync-db",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Sync extracted language rows to lang_data/lang_logs",
    )
    parser.add_argument("--db-table", default="lang_data", help="Language data table name")
    parser.add_argument("--logs-table", default="lang_logs", help="Language logs table name")
    parser.add_argument("--log-source", default="SYNC", help="lang_logs.source value")
    parser.add_argument("--log-status", default="APPROVED", help="lang_logs.status value")
    return parser.parse_args(argv)


def _load_scope_from_snapshot(snapshot_file: Path, route: str) -> tuple[str, str]:
    try:
        payload = load_snapshot_payload(snapshot_file)
        return resolve_route_scope(payload, route, snapshot_file)
    except (FileNotFoundError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc


def _normalize_text(value: str) -> str:
    return value.replace("\r\n", "\n").replace("\r", "\n")


def _decode_text_blob(blob: Any) -> str:
    if isinstance(blob, str):
        return blob
    if isinstance(blob, (bytes, bytearray)):
        raw = bytes(blob)
        for encoding in ("utf-8-sig", "utf-8", "utf-16", "utf-16-le", "utf-16-be", "cp932", "gb18030"):
            try:
                return raw.decode(encoding)
            except UnicodeDecodeError:
                continue
        return raw.decode("utf-8", errors="replace")
    return str(blob)


def _extract_entries_from_xml(xml_text: str) -> dict[str, str]:
    xml_text = xml_text.strip()
    if not xml_text:
        return {}

    try:
        root = ET.fromstring(xml_text)
        entries: dict[str, str] = {}
        for elem in root.findall(".//string"):
            key = (elem.attrib.get("name") or "").strip()
            if not key:
                continue
            value = "".join(elem.itertext())
            entries[key] = _normalize_text(value)
        if entries:
            return entries
    except ET.ParseError:
        pass

    entries = {}
    for match in STRING_TAG_PATTERN.finditer(xml_text):
        key = match.group(1).strip()
        value = html.unescape(match.group(2))
        entries[key] = _normalize_text(value)
    return entries


def _extract_text_asset_mapping(bundle_path: Path) -> dict[str, dict[str, str]]:
    found: dict[str, dict[str, str]] = {}
    env = UnityPy.load(str(bundle_path))

    for obj in env.objects:
        type_name = str(getattr(getattr(obj, "type", None), "name", "")).lower()
        if type_name != "textasset":
            continue

        asset = obj.read()
        asset_name = str(getattr(asset, "m_Name", getattr(asset, "name", ""))).strip()
        column = TARGET_TEXT_ASSETS.get(asset_name.lower())
        if not column:
            continue

        raw_text = getattr(asset, "m_Script", None)
        if raw_text is None:
            raw_text = getattr(asset, "script", None)
        text = _decode_text_blob(raw_text)
        entries = _extract_entries_from_xml(text)
        if not entries:
            continue

        previous = found.get(column)
        if previous is None or len(entries) > len(previous):
            found[column] = entries

    return found


def _build_rows(language_maps: dict[str, dict[str, str]], ko_map: dict[str, str]) -> list[dict[str, str]]:
    all_keys: set[str] = set()
    for data in language_maps.values():
        all_keys.update(data.keys())

    english_order = list(language_maps.get("en", {}).keys())
    ordered_keys: list[str] = []
    seen: set[str] = set()

    for key in english_order:
        if key in all_keys and key not in seen:
            ordered_keys.append(key)
            seen.add(key)

    for key in sorted(all_keys):
        if key not in seen:
            ordered_keys.append(key)

    rows: list[dict[str, str]] = []
    for key in ordered_keys:
        row = {
            "name": key,
            "cn_s": language_maps.get("cn_s", {}).get(key, ""),
            "en": language_maps.get("en", {}).get(key, ""),
            "jp": language_maps.get("jp", {}).get(key, ""),
            "cn_t": language_maps.get("cn_t", {}).get(key, ""),
            "ko": ko_map.get(key, ""),
        }
        rows.append(row)
    return rows


def _validate_table_name(table_name: str) -> str:
    return validate_table_name(table_name)


def _fetch_lang_db_rows(database_url: str, table_name: str) -> dict[str, dict[str, Any]]:
    sql = (
        f"SELECT name, cn_s, en, jp, cn_t, ko, is_deleted "
        f"FROM {table_name}"
    )

    mapping: dict[str, dict[str, Any]] = {}
    with psycopg.connect(database_url) as conn:  # type: ignore[union-attr]
        with conn.cursor() as cur:
            cur.execute(sql)
            for row in cur.fetchall():
                name = str(row[0] or "").strip()
                if not name:
                    continue
                mapping[name] = {
                    "cn_s": str(row[1] or ""),
                    "en": str(row[2] or ""),
                    "jp": str(row[3] or ""),
                    "cn_t": str(row[4] or ""),
                    "ko": str(row[5] or ""),
                    "is_deleted": bool(row[6]),
                }
    return mapping


def _build_ko_map_from_db(db_rows: dict[str, dict[str, Any]]) -> dict[str, str]:
    ko_map: dict[str, str] = {}
    for name, values in db_rows.items():
        ko = str(values.get("ko") or "").strip()
        if ko:
            ko_map[name] = ko
    return ko_map


def _build_lang_actions(
    rows: list[dict[str, str]],
    db_rows: dict[str, dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    creates: list[dict[str, Any]] = []
    updates: list[dict[str, Any]] = []
    restores: list[dict[str, Any]] = []
    deletes: list[dict[str, Any]] = []

    current_map: dict[str, dict[str, str]] = {
        str(row.get("name") or "").strip(): row for row in rows if str(row.get("name") or "").strip()
    }

    for name, row in current_map.items():
        current_nonko = {
            "cn_s": _normalize_text(str(row.get("cn_s") or "")),
            "en": _normalize_text(str(row.get("en") or "")),
            "jp": _normalize_text(str(row.get("jp") or "")),
            "cn_t": _normalize_text(str(row.get("cn_t") or "")),
        }
        current_ko = _normalize_text(str(row.get("ko") or ""))

        existing = db_rows.get(name)
        if existing is None:
            new_values = dict(current_nonko)
            if current_ko:
                new_values["ko"] = current_ko
            creates.append(
                {
                    "name": name,
                    "full_values": {**current_nonko, "ko": current_ko},
                    "old_values": None,
                    "new_values": new_values,
                }
            )
            continue

        existing_nonko = {
            "cn_s": _normalize_text(str(existing.get("cn_s") or "")),
            "en": _normalize_text(str(existing.get("en") or "")),
            "jp": _normalize_text(str(existing.get("jp") or "")),
            "cn_t": _normalize_text(str(existing.get("cn_t") or "")),
        }
        existing_ko = _normalize_text(str(existing.get("ko") or ""))
        is_deleted = bool(existing.get("is_deleted"))

        if is_deleted:
            old_values: dict[str, Any] = {"is_deleted": True}
            new_values: dict[str, Any] = {"is_deleted": False}
            for field in ("cn_s", "en", "jp", "cn_t"):
                if existing_nonko[field] != current_nonko[field]:
                    old_values[field] = existing_nonko[field]
                    new_values[field] = current_nonko[field]

            restores.append(
                {
                    "name": name,
                    "full_values": {**current_nonko, "ko": existing_ko},
                    "old_values": old_values,
                    "new_values": new_values,
                }
            )
            continue

        changed_old: dict[str, str] = {}
        changed_new: dict[str, str] = {}
        for field in ("cn_s", "en", "jp", "cn_t"):
            if existing_nonko[field] != current_nonko[field]:
                changed_old[field] = existing_nonko[field]
                changed_new[field] = current_nonko[field]

        if changed_new:
            updates.append(
                {
                    "name": name,
                    "full_values": {**current_nonko, "ko": existing_ko},
                    "old_values": changed_old,
                    "new_values": changed_new,
                }
            )

    current_keys = set(current_map.keys())
    for name, existing in db_rows.items():
        if name in current_keys:
            continue
        if bool(existing.get("is_deleted")):
            continue

        old_values = {
            "cn_s": _normalize_text(str(existing.get("cn_s") or "")),
            "en": _normalize_text(str(existing.get("en") or "")),
            "jp": _normalize_text(str(existing.get("jp") or "")),
            "cn_t": _normalize_text(str(existing.get("cn_t") or "")),
            "ko": _normalize_text(str(existing.get("ko") or "")),
            "is_deleted": False,
        }
        deletes.append(
            {
                "name": name,
                "old_values": old_values,
                "new_values": {"is_deleted": True},
            }
        )

    return {
        "creates": creates,
        "updates": updates,
        "restores": restores,
        "deletes": deletes,
    }


def _apply_lang_db_actions(
    database_url: str,
    data_table: str,
    logs_table: str,
    actions: dict[str, list[dict[str, Any]]],
    asset_version: str,
    log_source: str,
    log_status: str,
) -> dict[str, Any]:
    creates = actions["creates"]
    updates = actions["updates"]
    restores = actions["restores"]
    deletes = actions["deletes"]

    upsert_rows: list[tuple[Any, ...]] = []
    delete_rows: list[tuple[str]] = []
    log_rows: list[tuple[Any, ...]] = []

    batch_id = str(uuid.uuid4())

    for action_type, items in (("CREATE", creates), ("UPDATE", updates), ("RESTORE", restores)):
        for item in items:
            full_values = item["full_values"]
            ko_value = _normalize_text(str(full_values.get("ko") or "")).strip()
            upsert_rows.append(
                (
                    item["name"],
                    _normalize_text(str(full_values.get("cn_s") or "")),
                    _normalize_text(str(full_values.get("en") or "")),
                    _normalize_text(str(full_values.get("jp") or "")),
                    _normalize_text(str(full_values.get("cn_t") or "")),
                    ko_value if ko_value else None,
                )
            )

            old_json = item.get("old_values")
            new_json = item.get("new_values")
            log_rows.append(
                (
                    item["name"],
                    action_type,
                    json.dumps(old_json, ensure_ascii=False) if old_json is not None else None,
                    json.dumps(new_json, ensure_ascii=False) if new_json is not None else None,
                    log_source,
                    batch_id,
                    log_status,
                    asset_version,
                )
            )

    for item in deletes:
        delete_rows.append((item["name"],))
        log_rows.append(
            (
                item["name"],
                "DELETE",
                json.dumps(item.get("old_values"), ensure_ascii=False),
                json.dumps(item.get("new_values"), ensure_ascii=False),
                log_source,
                batch_id,
                log_status,
                asset_version,
            )
        )

    upsert_sql = (
        f"INSERT INTO {data_table} "
        f"(name, cn_s, en, jp, cn_t, ko, is_deleted, updated_at, latest_log_status, latest_log_date, last_external_at) "
        f"VALUES (%s, %s, %s, %s, %s, %s, false, NOW(), 'APPROVED', NOW(), NOW()) "
        f"ON CONFLICT (name) DO UPDATE SET "
        f"cn_s = EXCLUDED.cn_s, "
        f"en = EXCLUDED.en, "
        f"jp = EXCLUDED.jp, "
        f"cn_t = EXCLUDED.cn_t, "
        f"ko = COALESCE({data_table}.ko, EXCLUDED.ko), "
        f"is_deleted = false, "
        f"updated_at = NOW(), "
        f"latest_log_status = CASE WHEN {data_table}.latest_log_status = 'PENDING' THEN 'PENDING' ELSE 'APPROVED' END, "
        f"latest_log_date = NOW(), "
        f"last_external_at = NOW()"
    )

    delete_sql = (
        f"UPDATE {data_table} "
        f"SET is_deleted = true, updated_at = NOW(), last_external_at = NOW() "
        f"WHERE name = %s"
    )

    log_sql = (
        f"INSERT INTO {logs_table} "
        f"(name, action_type, old_value, new_value, source, batch_id, status, asset_version) "
        f"VALUES (%s, %s, %s::jsonb, %s::jsonb, %s, %s, %s, %s)"
    )

    with psycopg.connect(database_url) as conn:  # type: ignore[union-attr]
        with conn.cursor() as cur:
            if upsert_rows:
                cur.executemany(upsert_sql, upsert_rows)
            if delete_rows:
                cur.executemany(delete_sql, delete_rows)
            if log_rows:
                cur.executemany(log_sql, log_rows)
        conn.commit()

    return {
        "batch_id": batch_id,
        "create_count": len(creates),
        "update_count": len(updates),
        "restore_count": len(restores),
        "delete_count": len(deletes),
        "upsert_count": len(upsert_rows),
        "log_count": len(log_rows),
    }


def main(argv: list[str] | None = None) -> int:
    load_dotenv()
    args = parse_args(argv)
    args.input_root = resolve_repo_path(args.input_root).as_posix()
    args.report_file = resolve_repo_path(args.report_file).as_posix()
    args.snapshot_file = resolve_repo_path(args.snapshot_file).as_posix()

    version_arg = str(args.version or "").strip()
    revision_arg = str(args.revision or "").strip()
    if bool(version_arg) ^ bool(revision_arg):
        raise SystemExit("--version and --revision must be provided together")

    snapshot_file = _resolve_snapshot_file(Path(str(args.snapshot_file or DEFAULT_SNAPSHOT_FILE)))
    if version_arg and revision_arg:
        version = version_arg
        revision = revision_arg
    else:
        version, revision = _load_scope_from_snapshot(snapshot_file, DEFAULT_ROUTE)

    input_scope_dir = Path(args.input_root) / DEFAULT_ROUTE / version / revision

    if not input_scope_dir.exists():
        raise SystemExit(f"Input directory not found: {input_scope_dir}")

    bundle_paths = sorted(input_scope_dir.glob("*.bundle"))
    if not bundle_paths:
        raise SystemExit(f"No bundle files found in: {input_scope_dir}")

    aggregated: dict[str, dict[str, str]] = {}
    for bundle_path in bundle_paths:
        found = _extract_text_asset_mapping(bundle_path)
        for column, data in found.items():
            existing = aggregated.get(column)
            if existing is None or len(data) > len(existing):
                aggregated[column] = data

    missing_columns = [col for col in ("cn_s", "en", "jp", "cn_t") if col not in aggregated]
    if missing_columns:
        print(f"[assets-lang] warning: missing language assets for columns: {', '.join(missing_columns)}")

    db_sync_enabled = bool(args.sync_db)
    data_table = _validate_table_name(args.db_table)
    logs_table = _validate_table_name(args.logs_table)
    database_url = os.getenv("DATABASE_URL", "").strip()

    db_rows: dict[str, dict[str, Any]] = {}
    ko_map: dict[str, str] = {}
    ko_source = ""

    if database_url and psycopg is not None:
        db_rows = _fetch_lang_db_rows(database_url, data_table)
        ko_map = _build_ko_map_from_db(db_rows)
        ko_source = f"db:{data_table}"

    rows = _build_rows(aggregated, ko_map)

    db_apply: dict[str, Any] = {
        "enabled": db_sync_enabled,
        "applied": False,
        "batch_id": "",
        "create_count": 0,
        "update_count": 0,
        "restore_count": 0,
        "delete_count": 0,
        "upsert_count": 0,
        "log_count": 0,
        "data_table": data_table,
        "logs_table": logs_table,
    }

    actions: dict[str, list[dict[str, Any]]] = {
        "creates": [],
        "updates": [],
        "restores": [],
        "deletes": [],
    }

    if db_rows:
        actions = _build_lang_actions(rows, db_rows)

    if db_sync_enabled:
        if psycopg is None:
            raise SystemExit("psycopg is required for DB sync. Install with: pip install 'psycopg[binary]'")
        if not database_url:
            raise SystemExit("DATABASE_URL is required for DB sync")

        if not db_rows:
            db_rows = _fetch_lang_db_rows(database_url, data_table)
            actions = _build_lang_actions(rows, db_rows)

        applied = _apply_lang_db_actions(
            database_url=database_url,
            data_table=data_table,
            logs_table=logs_table,
            actions=actions,
            asset_version=f"{version}.{revision}",
            log_source=args.log_source,
            log_status=args.log_status,
        )
        db_apply.update(applied)
        db_apply["applied"] = True

    missing_ko_after_backfill = [row["name"] for row in rows if not (row.get("ko") or "").strip()]

    log_targets = {
        "create": sorted([item["name"] for item in actions["creates"]]),
        "update": sorted([item["name"] for item in actions["updates"]]),
        "restore": sorted([item["name"] for item in actions["restores"]]),
        "delete": sorted([item["name"] for item in actions["deletes"]]),
    }
    log_targets["all"] = sorted(set(log_targets["create"] + log_targets["update"] + log_targets["restore"] + log_targets["delete"]))

    report_payload = {
        "summary": {
            "route": DEFAULT_ROUTE,
            "version": version,
            "revision": revision,
            "snapshot_file": snapshot_file.as_posix(),
            "input_dir": input_scope_dir.as_posix(),
            "ko_source": ko_source,
            "bundle_count": len(bundle_paths),
            "row_count": len(rows),
            "backfilled_ko_count": sum(1 for row in rows if (row["name"] in ko_map and (row.get("ko") or "").strip())),
            "missing_ko_count": len(missing_ko_after_backfill),
            "db_sync_enabled": db_sync_enabled,
            "log_target_count": len(log_targets["all"]),
        },
        "log_targets": log_targets,
        "db_apply": db_apply,
    }

    report_path = Path(str(args.report_file or DEFAULT_LANG_REPORT_FILE))
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    print(
        "[assets-lang] "
        f"bundles={len(bundle_paths)} rows={len(rows)} "
        f"missing_ko={len(missing_ko_after_backfill)} log_targets={len(log_targets['all'])} db_sync={db_apply['applied']} report={report_path.as_posix()}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
